version: '3.4'

services:

  sqlserver:
    image: "mcr.microsoft.com/mssql/server:2019-latest"
    ports:
      - "1433:1433"
    environment:
      - "SA_PASSWORD=S3cur3P@ssW0rd!"
      - "ACCEPT_EULA=Y"

  webapi:
    image: ${DOCKER_REGISTRY-}webapi
    build:
      context: .
      dockerfile: src/Apps/ATSSystem.Api/Dockerfile
    ports:
      - "5005:80"

    restart: on-failure
    depends_on:
      - sqlserver