// <auto-generated />

using System;
using ATSSystem.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;

namespace ATSSystem.Infrastructure.SqlServer.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity("ATSSystem.Domain.Entities.Candidate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .UseIdentityColumn();

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Document")
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Seniority")
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Occupation")
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Curriculum")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Candidates");
                });

            modelBuilder.Entity("ATSSystem.Domain.Entities.Job", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("JobTitle")
                    .HasColumnType("nvarchar(100)");

                b.Property<string>("JobDiscription")
                    .HasColumnType("nvarchar(max)");

                b.Property<decimal>("Salary")
                    .HasColumnType("decimal");

                b.Property<string>("Seniority")
                    .HasColumnType("nvarchar(10)");

                b.HasKey("Id");

                b.ToTable("Job");
            });

            modelBuilder.Entity("ATSSystem.Domain.Entities.JobApplication", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("int")
                    .UseIdentityColumn();

                b.Property<string>("JobId")
                    .IsRequired()
                    .HasColumnType("int");

                b.Property<string>("CandidateId")
                    .IsRequired()
                    .HasColumnType("int");

                b.HasKey("Id");

                b.HasOne("ATSSystem.Domain.Entities.Job")
                 .WithMany()
                 .HasForeignKey("JobId");

                b.HasOne("ATSSystem.Domain.Entities.Candidate")
                 .WithMany()
                 .HasForeignKey("CandidateId");

                b.ToTable("JobApplication");
            });
        }
    }
}
