name: .NET

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET SDK 6.0
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x' 

    - name: Install dotnet ef
      run: dotnet tool install --global dotnet-ef

    - name: Install dependencies
      run: dotnet restore CleanArchitecture.sln

    - name: Build
      run: dotnet build CleanArchitecture.sln --configuration Release --no-restore
      
  test:
    name: Test
    runs-on: ubuntu-latest
    services:
      sql:
        image: mcr.microsoft.com/mssql/server
        ports:
          - 1433:1433
        env:
          SA_PASSWORD: Your_password123
          ACCEPT_EULA: Y
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET SDK 6.0
        uses: actions/setup-dotnet@v1
        with:
            dotnet-version: '6.0.x' 

      - name: run tests
        run: dotnet test CleanArchitecture.sln --configuration Release
        env:
          ConnectionStrings__DefaultConnection: Server=.;Database=CleanArchitectureTestDb;User=sa;Password=Your_password123;MultipleActiveResultSets=true
    
